# все категории в виде словаря
new_cats = [
    {"title": "Математика 🧮", "translations": {"en": "Mathematics 🧮"}},
    {"title": "Физика ⚛️", "translations": {"en": "Physics ⚛️"}},
    {"title": "Химия 🧪", "translations": {"en": "Chemistry 🧪"}},
    {"title": "Биология 🧬", "translations": {"en": "Biology 🧬"}},
    {"title": "Информатика 💻", "translations": {"en": "Computer Science 💻"}},
    {"title": "Инженерия ⚙️", "translations": {"en": "Engineering ⚙️"}},
    {"title": "Экономика 💰", "translations": {"en": "Economics 💰"}},
    {"title": "История 🏛️", "translations": {"en": "History 🏛️"}},
    {"title": "Философия 🤔", "translations": {"en": "Philosophy 🤔"}},
    {"title": "Социология 🫂", "translations": {"en": "Sociology 🫂"}},
    {"title": "Политология 🗳️", "translations": {"en": "Political Science 🗳️"}},
    {"title": "Психология 🧠", "translations": {"en": "Psychology 🧠"}},
    {"title": "Лингвистика 🗣️", "translations": {"en": "Linguistics 🗣️"}},
    {"title": "Литература 📚", "translations": {"en": "Literature 📚"}},
    {"title": "Искусство 🎨", "translations": {"en": "Art 🎨"}},
    {"title": "Музыка 🎶", "translations": {"en": "Music 🎶"}},
    {"title": "Медицина ⚕️", "translations": {"en": "Medicine ⚕️"}},
    {"title": "Право ⚖️", "translations": {"en": "Law ⚖️"}},
    {"title": "Педагогика 👨‍🏫", "translations": {"en": "Pedagogy 👨‍🏫"}},
    {"title": "География 🌍", "translations": {"en": "Geography 🌍"}},
    {"title": "Геология 🪨", "translations": {"en": "Geology 🪨"}},
    {"title": "Экология 🌿", "translations": {"en": "Ecology 🌿"}},
    {"title": "Астрономия ✨", "translations": {"en": "Astronomy ✨"}},
    {"title": "Архитектура 🏗️", "translations": {"en": "Architecture 🏗️"}},
    {"title": "Сельское хозяйство 🌾", "translations": {"en": "Agriculture 🌾"}},
    {"title": "Статистика 📈", "translations": {"en": "Statistics 📈"}},
    {"title": "Антропология 🐒", "translations": {"en": "Anthropology 🐒"}},
    {"title": "Археология 🏺", "translations": {"en": "Archaeology 🏺"}},
    {"title": "Иностранные языки 🌐", "translations": {
        "en": "Foreign Languages 🌐"}},
    {"title": "Авиация ✈️", "translations": {"en": "Aviation ✈️"}},
    {"title": "Космонавтика 🚀", "translations": {"en": "Cosmonautics 🚀"}},
    {"title": "Кибернетика 🤖", "translations": {"en": "Cybernetics 🤖"}},
    {"title": "Дизайн 📐", "translations": {"en": "Design 📐"}},
    {"title": "Образование 🎓", "translations": {"en": "Education 🎓"}},
    {"title": "Энергетика ⚡", "translations": {"en": "Energy ⚡"}},
    {"title": "Наука об окружающей среде 🏞️",
     "translations": {"en": "Environmental Science 🏞️"}},
    {"title": "Киноведение 🎬", "translations": {"en": "Film Studies 🎬"}},
    {"title": "Финансы 💸", "translations": {"en": "Finance 💸"}},
    {"title": "Гастрономия 🍳", "translations": {"en": "Gastronomy 🍳"}},
    {"title": "Генетика 🧬", "translations": {"en": "Genetics 🧬"}},
    {"title": "История искусств 🖼️", "translations": {"en": "Art History 🖼️"}},
    {"title": "Журналистика 📰", "translations": {"en": "Journalism 📰"}},
    {"title": "Управление 💼", "translations": {"en": "Management 💼"}},
    {"title": "Маркетинг 📊", "translations": {"en": "Marketing 📊"}},
    {"title": "Материаловедение 🔬", "translations": {
        "en": "Materials Science 🔬"}},
    {"title": "Нанотехнологии ⚛️", "translations": {"en": "Nanotechnology ⚛️"}},
    {"title": "Неврология 🧠", "translations": {"en": "Neurology 🧠"}},
    {"title": "Океанография 🌊", "translations": {"en": "Oceanography 🌊"}},
    {"title": "Фармацевтика 💊", "translations": {"en": "Pharmaceutics 💊"}},
    {"title": "Фотография 📷", "translations": {"en": "Photography 📷"}},
    {"title": "Робототехника 🦾", "translations": {"en": "Robotics 🦾"}},
    {"title": "Теология ✝️", "translations": {"en": "Theology ✝️"}},
    {"title": "Городское планирование 🏙️",
     "translations": {"en": "Urban Planning 🏙️"}},
    {"title": "Актуарная математика 🧮",
     "translations": {"en": "Actuarial Science 🧮"}},
    {"title": "Агрономия 🌱", "translations": {"en": "Agronomy 🌱"}},
    {"title": "Биохимия 🧪", "translations": {"en": "Biochemistry 🧪"}},
    {"title": "Биотехнологии 🧫", "translations": {"en": "Biotechnology 🧫"}},
    {"title": "Классическая филология 📜",
     "translations": {"en": "Classical Philology 📜"}},
    {"title": "Климатология ☀️", "translations": {"en": "Climatology ☀️"}},
    {"title": "Когнитивная наука 🧠", "translations": {
        "en": "Cognitive Science 🧠"}},
    {"title": "Вычислительная лингвистика 💻", "translations": {
        "en": "Computational Linguistics 💻"}},
    {"title": "Криминология 🕵️", "translations": {"en": "Criminology 🕵️"}},
    {"title": "Культурология 🎭", "translations": {"en": "Cultural Studies 🎭"}},
    {"title": "Демография 👪", "translations": {"en": "Demography 👪"}},
    {"title": "Разработка игр 🎮", "translations": {"en": "Game Development 🎮"}},
    {"title": "Генетика человека 🧬", "translations": {"en": "Human Genetics 🧬"}},
    {"title": "Гидрология 💧", "translations": {"en": "Hydrology 💧"}},
    {"title": "Иммунология 🦠", "translations": {"en": "Immunology 🦠"}},
    {"title": "Международные отношения 🌎", "translations": {
        "en": "International Relations 🌎"}},
    {"title": "Библиотечное дело 📚", "translations": {"en": "Library Science 📚"}},
    {"title": "Морская биология 🐠", "translations": {"en": "Marine Biology 🐠"}},
    {"title": "Математическая физика 🧮", "translations": {
        "en": "Mathematical Physics 🧮"}},
    {"title": "Механика ⚙️", "translations": {"en": "Mechanics ⚙️"}},
    {"title": "Метеорология ☁️", "translations": {"en": "Meteorology ☁️"}},
    {"title": "Микробиология 🔬", "translations": {"en": "Microbiology 🔬"}},
    {"title": "Молекулярная биология 🧬",
     "translations": {"en": "Molecular Biology 🧬"}},
    {"title": "Музыкальная теория 🎼", "translations": {"en": "Music Theory 🎼"}},
    {"title": "Ядерная физика ☢️", "translations": {"en": "Nuclear Physics ☢️"}},
    {"title": "Питание 🍎", "translations": {"en": "Nutrition 🍎"}},
    {"title": "Палеонтология 🦖", "translations": {"en": "Paleontology 🦖"}},
    {"title": "Фармакология 💊", "translations": {"en": "Pharmacology 💊"}},
    {"title": "Фотоника 💡", "translations": {"en": "Photonics 💡"}},
    {"title": "Физическая химия 🧪", "translations": {
        "en": "Physical Chemistry 🧪"}},
    {"title": "Физиология 🫀", "translations": {"en": "Physiology 🫀"}},
    {"title": "Науки о растениях 🌿", "translations": {"en": "Plant Science 🌿"}},
    {"title": "Полимерная химия 🧪", "translations": {
        "en": "Polymer Chemistry 🧪"}},
    {"title": "Квантовая механика ⚛️", "translations": {
        "en": "Quantum Mechanics ⚛️"}},
    {"title": "Радиобиология ☢️", "translations": {"en": "Radiobiology ☢️"}},
    {"title": "Социальная психология 🧠",
     "translations": {"en": "Social Psychology 🧠"}},
    {"title": "Теоретическая физика 칠판", "translations": {
        "en": "Theoretical Physics 칠판"}},
    {"title": "Токсикология ☠️", "translations": {"en": "Toxicology ☠️"}},
    {"title": "Ветеринария 🐾", "translations": {"en": "Veterinary Science 🐾"}},
    {"title": "Вирусология 🦠", "translations": {"en": "Virology 🦠"}},
    {"title": "Зоология 🦓", "translations": {"en": "Zoology 🦓"}},
    {"title": "Аналитическая философия 🔎",
     "translations": {"en": "Analytic Philosophy 🔎"}},
    {"title": "Поведенческая экономика 💰🤔",
     "translations": {"en": "Behavioral Economics 💰🤔"}},
    {"title": "Биоинформатика 🧬💻", "translations": {"en": "Bioinformatics 🧬💻"}},
    {"title": "Биомедицинская инженерия ⚙️⚕️",
     "translations": {"en": "Biomedical Engineering ⚙️⚕️"}},
    {"title": "Бизнес-администрирование 💼",
     "translations": {"en": "Business Administration 💼"}},
    {"title": "Химическая инженерия 🧪⚙️", "translations": {
        "en": "Chemical Engineering 🧪⚙️"}},
    {"title": "Гражданское строительство 🌉",
     "translations": {"en": "Civil Engineering 🌉"}},
    {"title": "Компьютерная инженерия 💻⚙️",
     "translations": {"en": "Computer Engineering 💻⚙️"}},
    {"title": "Сохранение данных 💾", "translations": {"en": "Data Science 💾"}},
    {"title": "Разработка программного обеспечения 👨‍💻",
     "translations": {"en": "Software Development 👨‍💻"}},
    {"title": "Электротехника 💡", "translations": {
        "en": "Electrical Engineering 💡"}},
    {"title": "Энергетическая инженерия ⚡⚙️",
     "translations": {"en": "Energy Engineering ⚡⚙️"}},
    {"title": "Инженерная геология 🪨⚙️", "translations": {
        "en": "Engineering Geology 🪨⚙️"}},
    {"title": "Инженерное управление ⚙️💼", "translations": {
        "en": "Engineering Management ⚙️💼"}},
    {"title": "Экологическая инженерия 🌿⚙️", "translations": {
        "en": "Environmental Engineering 🌿⚙️"}},
    {"title": "Экспериментальная психология 🧠🔬",
     "translations": {"en": "Experimental Psychology 🧠🔬"}},
    {"title": "Пищевая наука 🍎🔬", "translations": {"en": "Food Science 🍎🔬"}},
    {"title": "Лесное хозяйство 🌲", "translations": {"en": "Forestry 🌲"}},
    {"title": "Гендерные исследования ♀️♂️",
     "translations": {"en": "Gender Studies ♀️♂️"}},
    {"title": "Геотехническая инженерия 🌎⚙️", "translations": {
        "en": "Geotechnical Engineering 🌎⚙️"}},
    {"title": "Промышленный дизайн 🏭📐",
     "translations": {"en": "Industrial Design 🏭📐"}},
    {"title": "Информационные технологии ℹ️💻",
     "translations": {"en": "Information Technology ℹ️💻"}},
    {"title": "Интеллектуальная собственность ®️",
     "translations": {"en": "Intellectual Property ®️"}},
    {"title": "Машиностроение ⚙️", "translations": {
        "en": "Mechanical Engineering ⚙️"}},
    {"title": "Медицинская антропология ⚕️🐒",
     "translations": {"en": "Medical Anthropology ⚕️🐒"}},
    {"title": "Мехатроника 🤖⚙️", "translations": {"en": "Mechatronics 🤖⚙️"}},
    {"title": "Горное дело ⛏️", "translations": {"en": "Mining Engineering ⛏️"}},
    {"title": "Музыкальная история 🎶🏛️",
     "translations": {"en": "Music History 🎶🏛️"}},
    {"title": "Наука о данных 📊💻", "translations": {"en": "Data Science 📊💻"}},
    {"title": "Сестринское дело 👩‍⚕️", "translations": {"en": "Nursing 👩‍⚕️"}},
    {"title": "Нефтегазовая инженерия 🛢️⚙️", "translations": {
        "en": "Petroleum Engineering 🛢️⚙️"}},
    {"title": "Связи с общественностью 📢",
     "translations": {"en": "Public Relations 📢"}},
    {"title": "Квантовая химия ⚛️🧪", "translations": {
        "en": "Quantum Chemistry ⚛️🧪"}},
    {"title": "Наука о религии 🛐", "translations": {"en": "Religious Studies 🛐"}},
    {"title": "Системная инженерия ⚙️", "translations": {
        "en": "Systems Engineering ⚙️"}},
    {"title": "Транспортная инженерия 🚗🚂✈️", "translations": {
        "en": "Transportation Engineering 🚗🚂✈️"}}
]
